Добавлена функционал финального проекта №10.
Azaman32/java-filmorate pull request #2
Opened 2022-09-03 14:16 UTC by Azaman32

Добавление в друзья и рейтинг фильмов.

2022-09-04 21:55 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmValidator validationFilms = new FilmValidator();
название поля должно быть `filmValidator`
а инициализироваться оно должно также спрингом в конструкторе

2022-09-04 21:56 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new UserNotFoundException("Invalid id");
по такому сообщению в исключении совсем непонятно, что произошло: там нет ни самого ид, ни причины, почему он invalid

лучше:
`"User with id " + id + " not found"`

2022-09-04 21:59 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmValidator.java
> +            throw new UserNotFoundException("Invalid id");
тут тоже нужно поменять исключение и сообщение

2022-09-04 22:00 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final UserValidator userValidator = new UserValidator();
UserValidator тоже нужно сделать компонентом сприна и инициализировать через внедрение зависимостей, как userService

2022-09-04 22:00 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public void deleteFriend(@PathVariable("id") int id, @PathVariable("friendId") int friendId) {
первый аргумент лучше назвать currentUserId, чтобы было понятнее что за id передается

2022-09-04 22:01 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final FilmIdGenerator filmIdGenerator = new FilmIdGenerator();
тоже нужно сделать компонентом

2022-09-04 22:03 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public void filmExist(int id) {
чтобы каждый раз не проверять, есть ли сущность в хранилище, лучше бросать исключение в методе getFilm если его нет, а если есть, то возвращать его

2022-09-04 22:04 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private final UserIdGenerator userIdGenerator = new UserIdGenerator();
тут тоже надо сделать бином

2022-09-04 22:06 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        userStorage.get(userId).getFriends().remove(friendId);
как писал выше, стоит в методе get сделать исключение, если нет фильма, тогда такие методы будут проще выглядеть 

также походы в бд - это относительно дорогая по времени операция, поэтому стараются уменьшить количество запросов к ней

2022-09-04 22:06 UTC, makholin requested changes
Нужно исправить замечания

2022-09-05 14:39 UTC, Azaman32 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new UserNotFoundException("Invalid id");
Но если я сделаю ValidationException то Postman ругается что должно быть 404 а не 400

2022-09-05 15:36 UTC, Azaman32 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        userStorage.get(userId).getFriends().remove(friendId);
В классе UserService, метод get вызывается не всегда когда нужна проверка User на null (в некоторых методах вызов get не требуется). Надо вызывать get везде где требуется проверка или можно оставить так?

2022-09-06 23:24 UTC, makholin approved these changes
Работа принята

2022-09-08 13:39 UTC, merged